version: '3'
services: 

  frontend:    
    build:      
      context: ./frontend    
    ports:      
      - "3000:3000"    
    depends_on:      
      - backend  
  
  backend:    
      build:      
        context: ./backend    
      ports:      
        - "4000:4000"       
      depends_on:      
        - db  
        
  db:    
    image: postgres:13    
    environment:      
      POSTGRES_DB: paperdb      
      POSTGRES_USER: user      
      POSTGRES_PASSWORD: password    
    
    volumes:      
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql